[pytest]
testpaths = "tests"
python_paths=".:tests/"
# Directories that are not visited by pytest collector:
norecursedirs = *.egg .eggs dist build docs .tox .git __pycache__

# You will need to measure your tests speed with `-n auto` and without it,
# so you can see whether it gives you any performance gain, or just gives
# you an overhead. See `docs/template/development-process.rst`.
addopts =
  -vl
  --strict
  --tb=auto
  --cov=compat_patcher
  --cov-report=html
